-- ====================================================================
-- NeoDB Studio - Oracle 多言語スキーマ構築＋1,000件データ投入
-- ====================================================================
-- 目的     : neodb スキーマ（ユーザー）を作成し、英語・日本語の 1,000 件超のリレーションデータを投入
-- 適用先   : neodb-oracle コンテナ (PDB: FREEPDB1)
-- 注意事項 : Oracle 公式イメージには docker-entrypoint-initdb.d 相当の仕組みが無いため、
--            本ファイルは Scripts\apply_seed.ps1 から sqlplus 経由で SYSTEM ユーザーとして適用する。
--            NeoDB Studio のスキーマ解析は USER_TAB_COLUMNS（接続ユーザー自身のスキーマ）を参照するため、
--            SYSTEM ではなく専用ユーザー neodb を作成し、その配下へオブジェクトを作成する。
-- 著作権   : Copyright (c) 2026 オリオンシステムズ. All Rights Reserved.

SET DEFINE OFF
SET SERVEROUTPUT ON

-- 1. 専用ユーザー (スキーマ) の作成。既に存在する場合は再作成する
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'NEODB';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER neodb CASCADE';
    END IF;
END;
/

CREATE USER neodb IDENTIFIED BY "Password123!";
GRANT CONNECT, RESOURCE TO neodb;
ALTER USER neodb QUOTA UNLIMITED ON USERS;

-- 2. ユーザーマスタテーブル (users)
CREATE TABLE neodb.users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ユーザーID (自動採番)
    user_code     VARCHAR2(20)  NOT NULL UNIQUE,                        -- ユーザーコード
    username_en   VARCHAR2(100) NOT NULL,                               -- 氏名 (英語)
    username_ja   NVARCHAR2(100) NOT NULL,                              -- 氏名 (日本語)
    email         VARCHAR2(255) NOT NULL,                               -- メールアドレス
    department_ja NVARCHAR2(100) NOT NULL,                              -- 所属部署 (日本語)
    role_ja       NVARCHAR2(100) NOT NULL,                              -- 役職 (日本語)
    salary        NUMBER(12, 2) NOT NULL,                               -- 給与額
    is_active     NUMBER(1) DEFAULT 1,                                  -- 有効フラグ (1:有効 / 0:無効)
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP                        -- 登録日時
);

-- 3. 商品マスタテーブル (products)
CREATE TABLE neodb.products (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 商品ID (自動採番)
    sku             VARCHAR2(50)  NOT NULL UNIQUE,                        -- 商品コード (SKU)
    product_name_en VARCHAR2(200) NOT NULL,                               -- 商品名 (英語)
    product_name_ja NVARCHAR2(200) NOT NULL,                              -- 商品名 (日本語)
    category_ja     NVARCHAR2(100) NOT NULL,                              -- カテゴリ (日本語)
    unit_price      NUMBER(10, 2) NOT NULL,                               -- 単価
    stock_quantity  NUMBER NOT NULL,                                      -- 在庫数
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP                        -- 登録日時
);

-- 4. 注文トランザクションテーブル (orders)
CREATE TABLE neodb.orders (
    order_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 注文ID (自動採番)
    order_no          VARCHAR2(30) NOT NULL UNIQUE,                         -- 注文番号
    user_id           NUMBER NOT NULL,                                      -- ユーザーID (users.user_id)
    product_id        NUMBER NOT NULL,                                      -- 商品ID (products.product_id)
    quantity          NUMBER NOT NULL,                                      -- 数量
    unit_price        NUMBER(10, 2) NOT NULL,                               -- 単価
    total_amount      NUMBER(12, 2) NOT NULL,                               -- 合計金額
    payment_status_ja NVARCHAR2(50) NOT NULL,                               -- 決済ステータス (日本語)
    ordered_at        TIMESTAMP DEFAULT SYSTIMESTAMP,                       -- 注文日時
    CONSTRAINT fk_orders_user    FOREIGN KEY (user_id)    REFERENCES neodb.users(user_id)       ON DELETE CASCADE,
    CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES neodb.products(product_id) ON DELETE CASCADE
);

-- 5. 商品マスタ初期データの投入
INSERT INTO neodb.products (product_id, sku, product_name_en, product_name_ja, category_ja, unit_price, stock_quantity)
VALUES (1, 'SKU-1001', 'Enterprise Database Cloud Cluster',  N'エンタープライズ DB クラウドクラスタ', N'データベース基盤', 1280000.00, 50);
INSERT INTO neodb.products (product_id, sku, product_name_en, product_name_ja, category_ja, unit_price, stock_quantity)
VALUES (2, 'SKU-1002', 'AI Model Acceleration Processor',    N'AI アクセラレータプロセッサ',           N'ハードウェア',     450000.00, 120);
INSERT INTO neodb.products (product_id, sku, product_name_en, product_name_ja, category_ja, unit_price, stock_quantity)
VALUES (3, 'SKU-1003', 'Zero-Trust Security Gateway Module', N'ゼロトラスト セキュリティモジュール',   N'ネットワーク',     320000.00, 80);
INSERT INTO neodb.products (product_id, sku, product_name_en, product_name_ja, category_ja, unit_price, stock_quantity)
VALUES (4, 'SKU-1004', 'High-Speed NVMe Storage Array',      N'超高速 NVMe ストレージアレイ',         N'ストレージ',       680000.00, 45);
INSERT INTO neodb.products (product_id, sku, product_name_en, product_name_ja, category_ja, unit_price, stock_quantity)
VALUES (5, 'SKU-1005', 'Automated DevOps Pipeline License',  N'自動化 DevOps パイプラインライセンス', N'ソフトウェア',     150000.00, 500);

-- 6. ユーザー 1,000 件の投入（CONNECT BY による連番生成）
INSERT INTO neodb.users (user_id, user_code, username_en, username_ja, email, department_ja, role_ja, salary, is_active, created_at)
SELECT
    i,
    'USR-' || LPAD(TO_CHAR(i), 5, '0'),
    'Engineer_' || TO_CHAR(i),
    N'開発エンジニア_' || TO_CHAR(i) || N' 氏',
    'engineer_' || TO_CHAR(i) || '@orionsystems.jp',
    DECODE(MOD(i, 5), 0, N'基盤システム開発部', 1, N'クラウドインフラ部', 2, N'DBA運用統括課', 3, N'セキュリティ監査室', N'先端AI研究部'),
    DECODE(MOD(i, 4), 0, N'リードアーキテクト', 1, N'シニアデータベースエンジニア', 2, N'スペシャリスト', N'運用マネージャー'),
    450000.00 + MOD(i * 3500, 450000),
    CASE WHEN MOD(i, 15) = 0 THEN 0 ELSE 1 END,
    SYSTIMESTAMP - NUMTODSINTERVAL(i, 'HOUR')
FROM (SELECT LEVEL AS i FROM dual CONNECT BY LEVEL <= 1000);

-- 7. 注文 1,000 件の投入（users / products への外部キーを保持）
INSERT INTO neodb.orders (order_id, order_no, user_id, product_id, quantity, unit_price, total_amount, payment_status_ja, ordered_at)
SELECT
    i,
    'ORD-DKR-' || LPAD(TO_CHAR(i), 6, '0'),
    i,
    MOD(i, 5) + 1,
    MOD(i, 8) + 1,
    DECODE(MOD(i, 5) + 1, 1, 1280000.00, 2, 450000.00, 3, 320000.00, 4, 680000.00, 150000.00),
    (MOD(i, 8) + 1) * DECODE(MOD(i, 5) + 1, 1, 1280000.00, 2, 450000.00, 3, 320000.00, 4, 680000.00, 150000.00),
    DECODE(MOD(i, 4), 0, N'決済完了 (Paid)', 1, N'出荷準備中 (Processing)', 2, N'発送済み (Shipped)', N'キャンセル (Cancelled)'),
    SYSTIMESTAMP - NUMTODSINTERVAL(i * 20, 'MINUTE')
FROM (SELECT LEVEL AS i FROM dual CONNECT BY LEVEL <= 1000);

COMMIT;

EXIT
