<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- アナライザー警告の非表示抑止設定 -->
    <NoWarn>NU1701;NU1603;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="AvalonEdit" Version="6.3.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.60.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <!-- MSAGL一式を明示的に指定 -->
    <PackageReference Include="AutomaticGraphLayout" Version="1.1.12" />
    <PackageReference Include="AutomaticGraphLayout.Drawing" Version="1.1.12" />
    <PackageReference Include="AutomaticGraphLayout.WpfGraphControl" Version="1.1.12" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeoDbStudio.Shared\NeoDbStudio.Shared.csproj" />
    <ProjectReference Include="..\..\UndoRedoKit\src\UndoRedoKit\UndoRedoKit.csproj" />
    <ProjectReference Include="..\..\UndoRedoKit\src\UndoRedoKit.Extensions.DependencyInjection\UndoRedoKit.Extensions.DependencyInjection.csproj" />
  </ItemGroup>
</Project>